/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.InvoiceActionListener;

import java.awt.event.ActionListener;
import javax.swing.JTextField;

/**
 * @author Aya.Mohamed
 */
public class NewInvoiceItemPage extends javax.swing.JFrame {
    private ActionListener controller;

    /**
     * Creates new form NewInvoiceItemPage
     *
     * @param <error>
     */
    public NewInvoiceItemPage(InvoiceForm form) {
        controller = new InvoiceActionListener(form);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        invoiceNumTxt = new javax.swing.JTextField();
        itemNameTxt = new javax.swing.JTextField();
        itemPriceTxt = new javax.swing.JTextField();
        countTxt = new javax.swing.JTextField();
        invoiceItemOkBtn = new javax.swing.JButton();
        invoiceItemOkBtn.addActionListener(controller);
        invoiceItemCancelBtn = new javax.swing.JButton();
        invoiceItemCancelBtn.addActionListener(controller);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Invoice Item Page");

        jLabel1.setText("Invoice Number");

        jLabel2.setText("Item Name");

        jLabel3.setText("Item Price");

        jLabel4.setText("Count");

        invoiceNumTxt.setEnabled(false);

        invoiceItemOkBtn.setText("Ok");
        invoiceItemOkBtn.setActionCommand("Ok Invoice Item");

        invoiceItemCancelBtn.setText("Cancel");
        invoiceItemCancelBtn.setActionCommand("Cancel Invoice Item");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(invoiceItemOkBtn))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(invoiceNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invoiceItemCancelBtn))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(invoiceNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(itemNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(itemPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(countTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invoiceItemCancelBtn)
                    .addComponent(invoiceItemOkBtn))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        invoiceItemOkBtn.getAccessibleContext().setAccessibleName("Ok Invoice Item");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField countTxt;
    private javax.swing.JButton invoiceItemCancelBtn;
    private javax.swing.JButton invoiceItemOkBtn;
    private javax.swing.JTextField invoiceNumTxt;
    private javax.swing.JTextField itemNameTxt;
    private javax.swing.JTextField itemPriceTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    public JTextField getCountTxt() {
        return countTxt;
    }

    public void setCountTxt(JTextField countTxt) {
        this.countTxt = countTxt;
    }

    public JTextField getInvoiceNumTxt() {
        return invoiceNumTxt;
    }

    public void setInvoiceNumTxt(JTextField invoiceNumTxt) {
        this.invoiceNumTxt = invoiceNumTxt;
    }

    public JTextField getItemNameTxt() {
        return itemNameTxt;
    }

    public void setItemNameTxt(JTextField itemNameTxt) {
        this.itemNameTxt = itemNameTxt;
    }

    public JTextField getItemPriceTxt() {
        return itemPriceTxt;
    }

    public void setItemPriceTxt(JTextField itemPriceTxt) {
        this.itemPriceTxt = itemPriceTxt;
    }


}
