/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.InvoiceActionListener;
import com.toedter.calendar.JDateChooser;

import java.awt.event.ActionListener;
import javax.swing.JTextField;

/**
 * @author Aya.Mohamed
 */
public class NewInvoiceHeaderPage extends javax.swing.JFrame {

    private ActionListener controller;

    /**
     * Creates new form NewInvoiceHeaderPage
     */
    public NewInvoiceHeaderPage(InvoiceForm form) {
        controller = new InvoiceActionListener(form);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        invoiceNumTxt = new javax.swing.JTextField();
        customerNameTxt = new javax.swing.JTextField();
        okInvoiceHeaderBtn = new javax.swing.JButton();
        okInvoiceHeaderBtn.addActionListener(controller);

        cancelInvoiceHeaderBtn = new javax.swing.JButton();
        dateTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Invoice Header Page");

        jLabel1.setText("Invoice Number");

        jLabel2.setText("Customer Name");

        jLabel3.setText("Date");

        invoiceNumTxt.setEnabled(false);

        okInvoiceHeaderBtn.setText("Ok");
        okInvoiceHeaderBtn.setActionCommand("Ok Invoice Header");

        cancelInvoiceHeaderBtn.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(okInvoiceHeaderBtn))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(invoiceNumTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                                        .addComponent(customerNameTxt))
                                                .addComponent(cancelInvoiceHeaderBtn))
                                        .addComponent(dateTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(invoiceNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(customerNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(okInvoiceHeaderBtn)
                                        .addComponent(cancelInvoiceHeaderBtn))
                                .addContainerGap(74, Short.MAX_VALUE))
        );

        okInvoiceHeaderBtn.getAccessibleContext().setAccessibleName("Ok Invoice Header");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelInvoiceHeaderBtn;
    private javax.swing.JTextField customerNameTxt;
    private javax.swing.JTextField dateTxt;
    private javax.swing.JTextField invoiceNumTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton okInvoiceHeaderBtn;
    // End of variables declaration//GEN-END:variables

    public JTextField getCustomerNameTxt() {
        return customerNameTxt;
    }

    public void setCustomerNameTxt(JTextField customerNameTxt) {
        this.customerNameTxt = customerNameTxt;
    }

    public JTextField getDateTxt() {
        return dateTxt;
    }

    public void setDateTxt(JTextField dateTxt) {
        this.dateTxt = dateTxt;
    }


    public JTextField getInvoiceNumTxt() {
        return invoiceNumTxt;
    }

    public void setInvoiceNumTxt(JTextField invoiceNumTxt) {
        this.invoiceNumTxt = invoiceNumTxt;
    }


}
